{% set name = "highered" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/highered-{{ version }}.tar.gz
  sha256: 5fcae90599dda98560d6f5347ff88aee56a4b8e7181d009852c3dc699c336fb7

build:
  skip: True  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - numpy
    - pyhacrf-datamade >=0.2.0
    - python

test:
  imports:
    - highered
  requires:
    - pip
  commands:
    - pip check
    # in the absence of tests, try a line from example.py
    - python -c "import highered; ed = highered.CRFEditDistance()"

about:
  home: https://github.com/dedupeio/highered
  summary: Learnable Edit Distance Using PyHacrf
  description: |
    CRF Edit Distance
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://github.com/dedupeio/highered
  dev_url: https://github.com/dedupeio/highered

extra:
  recipe-maintainers:
    - osamples
    - izahn
